# Generated by Django 2.2.3 on 2019-07-31 10:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    replaces = [('family_tree', '0001_initial'), ('family_tree', '0002_auto_20190731_0948'), ('family_tree', '0003_auto_20190731_0951'), ('family_tree', '0004_person_birth_date'), ('family_tree', '0005_auto_20190731_1200'), ('family_tree', '0006_auto_20190731_1210')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_names', models.CharField(blank=True, default='', max_length=83)),
                ('last_name', models.CharField(max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=131, null=True)),
                ('parent_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parenta', to='family_tree.Person')),
                ('gender', models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female'), ('d', 'diverse')], max_length=1, null=True)),
                ('birth_date', models.DateField(default=datetime.datetime(2019, 7, 31, 9, 55, 1, 168612, tzinfo=utc))),
                ('parent_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parentb', to='family_tree.Person')),
            ],
        ),
    ]
