# Generated by Django 2.2.3 on 2019-07-31 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0001_squashed_0006_auto_20190731_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='parent_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parenta', to='family_tree.Person', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='person',
            name='parent_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parentb', to='family_tree.Person', verbose_name='Parent'),
        ),
    ]
