# Generated by Django 2.2.3 on 2019-07-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0003_person_death_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics/'),
        ),
    ]
