# Generated by Django 2.2.3 on 2019-07-31 09:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0003_auto_20190731_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 31, 9, 55, 1, 168612, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
