# Generated by Django 2.2.3 on 2019-08-01 19:58

from django.db import migrations, models
import django.db.models.deletion
import family_tree.models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0004_person_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='parent_a',
        ),
        migrations.RemoveField(
            model_name='person',
            name='parent_b',
        ),
        migrations.AlterField(
            model_name='person',
            name='death_date',
            field=models.DateField(blank=True, null=True, validators=[family_tree.models.validate_dates]),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Upload photo'),
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(blank=True, choices=[('p', 'partnered'), ('e', 'engaged'), ('m', 'married'), ('d', 'divorced')], max_length=1, null=True)),
                ('person_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persona', to='family_tree.Person', verbose_name='Partner')),
                ('person_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personb', to='family_tree.Person', verbose_name='Partner')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='parents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to='family_tree.Relationship', verbose_name='Parent Relation'),
        ),
    ]
