# Generated by Django 2.2.3 on 2019-08-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0005_auto_20190801_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'people'},
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='photos/', verbose_name='Upload photo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relation_type',
            field=models.CharField(choices=[('p', 'partnered'), ('e', 'engaged'), ('m', 'married'), ('d', 'divorced'), ('o', 'other')], default='o', max_length=1),
            preserve_default=False,
        ),
    ]
